bin/gw_summary, gwsumm/archive.py, gwsumm/channels.py, gwsumm/data.py, gwsumm/plot/builtin.py, gwsumm/plot/core.py, gwsumm/tabs/data.py, gwsumm/tabs/hveto.py
This PR greatly improves the data handling for spectrograms as follows
- fixed archiving of spectrograms
- only read timeseries during spectrogram times (so you don't read the whole timeseries every time)
=> Improved spectrogram data handling

gwsumm/plot/builtin.py, gwsumm/tabs/management.py
This PR introduces improvements to the way that colors for known and active segments are parsed and used in the `SegmentDataPlot`.
Associated changes are made to the `AccountingTab` to colour the segments by the category colors (as used in the pie chart).
=> Improved segment plot color parsing

gwsumm/data.py, gwsumm/tabs/guardian.py
This PR fixes errors introduces by the latest non-backwards-compatible beta release of GWpy (0.1b3).
=> Fixes for GWpy 0.1b3 compatibility

gwsumm/tabs/__init__.py, gwsumm/tabs/fscan.py
This PR introduces the FscanTab, for summarising the results of an FScan analysis.
=> New FscanTab

gwsumm/plot/builtin.py, gwsumm/tabs/data.py
- StateVectorDataPlot: can specify subset of bits to plot
- give 'bits' option in the config as a list of bit numbers to
display
- ODCDataPlot: can specify the bitmask channel manually, defaults to
finding the standard ODC bitmask channel
=> Some new features for statevector plots

bin/gw_summary, gwsumm/data.py, gwsumm/tabs/data.py
- gw_summary now accepts --on-datafind-error {raise|warn|ignore}
- all methods that end up in _get_timeseries_dict now accept
datafind_error='raise' kwarg
- DataTab.process now handles datafind_error passing as well
=> Added error handling for datafind errors

bin/gw_summary, gwsumm/plot/builtin.py, gwsumm/plot/core.py, gwsumm/tabs/data.py, gwsumm/tabs/ihope.py, gwsumm/utils.py
This PR introduces a re-worked version of the plot multiprocessing that should fix the recent problems on LDAS with improper process/queue closure.
=> Re-worked multiprocessing of figure generation

gwsumm/data.py, gwsumm/plot/__init__.py, gwsumm/plot/builtin.py, gwsumm/plot/range.py, gwsumm/tabs/data.py
This PR implements custom inspiral and burst range calculations through a new `data.get_xxx` method, and associated plot classes.
=> New sensitive range calculation methods

gwsumm/plot/core.py, gwsumm/plot/segments.py, gwsumm/tabs/guardian.py
This PR introduces the `SegmentBarPlot` with new base classes `BarPlot` and `PiePlot`. This also configures new pie and bar plots for the `GuardianTab`.
=> New guardian plots

gwsumm/plot/builtin.py, gwsumm/plot/segments.py, gwsumm/tabs/management.py
As per a request from LIGO Lab, I have added a stacked bar chart to the `AccountingTab`.
This PR introduces the `stacked` option for the `DutyDataPlot` class, and fixes a couple of other related features/bugs along the way.
=> New stacked bar chart for accounting tabs

gwsumm/plot/range.py, gwsumm/tabs/data.py, gwsumm/utils.py
This PR adds two new plots for displaying time x volume:
- `'time-volume'` takes range channel and flag and calculates VT
- `'strain-time-volume'` takes strain channel and flag, calculates range, then calculates VT
This is the first type of plot that has both channels and flags, so I had to adjust a couple of small things to accommodate.
=> Added time-volume plots

gwsumm/plot/builtin.py
Adds a new kind of DataPlot, subclassed from TimeSeriesHistogramDataPlot, that produces 2D histograms for two given channels. An example of the output can be found here: https://ldas-jobs.ligo.caltech.edu/~max.isi/gwsumm_hist2d/day/20151114/
=> TimeSeriesHistogram2dDataPlot

.gitignore, bin/gw_summary, gwsumm/archive.py, gwsumm/config.py, gwsumm/state/__init__.py, gwsumm/tabs/core.py
This PR introduces a re-factoring of the `gw_summary` command-line script, mainly moving a lot of configuration-file parsing into the `gwsumm.config` module.
=> Re-factoring of `gw_summary` script

.travis.yml, .travis/build-nds2.sh, gwsumm/archive.py, gwsumm/tabs/guardian.py, gwsumm/tests/test_archive.py, gwsumm/tests/test_data.py, gwsumm/tests/test_plot.py, gwsumm/tests/test_tabs.py, requirements.txt, setup.py
This PR introduces more unit tests for the `gwsumm` package.
=> More unit tests

gwsumm/channels.py, gwsumm/data.py, gwsumm/tabs/core.py, gwsumm/tabs/data.py, gwsumm/tests/test_archive.py
This PR improves the 'Channel Information' and 'Segment information' tables in the `DataTab` HTML output.
Additionally this fixes one bug introduced in an earlier PR.
This fixes #44.
=> Improved channel and segment information display in DataTab

gwsumm/tabs/data.py, gwsumm/tabs/etg.py
Reverts gwpy/gwsumm#38
This may be causing problems with multiprocessed plotting.
=> Revert "Raise all plot exceptions"

.travis.yml, gwsumm/triggers.py, requirements.txt, setup.py
This PR modifes `gwsumm.triggers.get_triggers` to use the new [trigfind](//github.com/ligovirgo/trigfind) package for all automatic trigger queries.
=> Use trigfind package for trigger file discovery

gwsumm/data.py, gwsumm/plot/builtin.py
This PR updates gwsumm to use the new `gwpy.frequencyseries.FrequencySeries` object, which fixes a few errors, mainly in plotting
=> Use gwpy.frequencyseries.FrequencySeries

.travis.yml, gwsumm/plot/mixins.py, requirements.txt, setup.py
This PR re-worked the travis-ci.org build-and-test configuration, we need to test both python 2.6 and python 2.7 at least.
=> Re-worked travis configuration

.gitignore, .travis.yml, gwsumm/tabs/builtin.py, gwsumm/tabs/core.py, gwsumm/tests/test_archive.py, gwsumm/tests/test_channels.py, gwsumm/tests/test_data.py, gwsumm/tests/test_mode.py, gwsumm/tests/test_plot.py, gwsumm/tests/test_tabs.py, requirements.txt, setup.py
This PR adds a small set of basic unit tests for the `Tab`, `ExternalTab`, `PlotTab` and `Archived...` equivalents. Not much, but a start.
=> Added first unit tests for Tab objects

gwsumm/channels.py, gwsumm/config.py, gwsumm/data.py, gwsumm/plot/builtin.py, gwsumm/plot/core.py, gwsumm/plot/range.py, gwsumm/tabs/data.py, gwsumm/utils.py
This PR fixes a few bugs in the handling of GEO data channels.
=> Bug fixes for handling GEO channels

gwsumm/data.py, gwsumm/plot/builtin.py, gwsumm/tabs/data.py, gwsumm/tests/test_data.py
This PR fixes a small set of errors in processing coherence spectra and spectrograms.
=> Fixed errors in coherence processing

gwsumm/triggers.py
This PR introduces a new syntax for declaring keyword arguments to pass to `GWRecArray.read`; options in the `[etg]` section just get parsed and passed to the reader.
=> Defined new syntax for kwargs for the trigger reader

gwsumm/config.py, gwsumm/data/coherence.py, gwsumm/data/spectral.py, gwsumm/plot/core.py, gwsumm/plot/segments.py, gwsumm/tabs/data.py, gwsumm/tabs/guardian.py, gwsumm/triggers.py, gwsumm/utils.py
This PR introduces an improved parsing of segment colours, mainly via the `active` and `known` configuration parameters.
Included also is a new `safe_eval` function to replace all the `try/except SyntaxError` clauses when `eval`-ing configuration parameters, and a move of the massive list of draw parameters used in `DataPlot.parse_plot_kwargs` to a class attribute.
=> Improved parsing of segment colours

gwsumm/tests/test_utils.py, gwsumm/utils.py
This PR introduces a set of unit tests for the `gwsumm.utils` module, and fixes a couple of problems uncovered along-the-way.
=> Added unit tests for gwsumm.utils

gwsumm/plot/range.py
This PR fixes two bugs in range plotting
- empty range plots break
- parsing unit names to force `Mpc` was broken
=> Fixed two bugs in range plotting (empty/units)

gwsumm/html/bootstrap/__init__.py, gwsumm/tabs/core.py, share/js/gwsumm.js, share/sass/gwsumm.scss
This PR fixes a few small HTML issues, mainly with formatting for mobile screens.
=> Corrected a few miscellaneous HTML issues

gwsumm/channels.py, gwsumm/data/timeseries.py, gwsumm/data/utils.py, gwsumm/plot/builtin.py, gwsumm/plot/core.py, gwsumm/plot/range.py, gwsumm/plot/segments.py, gwsumm/plot/triggers.py, gwsumm/segments.py, gwsumm/tabs/core.py, gwsumm/tabs/data.py, gwsumm/tabs/etg.py, gwsumm/tabs/fscan.py, gwsumm/tabs/gracedb.py, gwsumm/tabs/guardian.py, gwsumm/tabs/hveto.py, gwsumm/tabs/management.py, gwsumm/tabs/registry.py, gwsumm/tabs/stamp.py, gwsumm/tests/test_archive.py, gwsumm/tests/test_mode.py, gwsumm/tests/test_tabs.py
This PR fixes a number of `pyflakes` complaints, mainly unused imports/variables.
=> Fixed myraid complaints from `pyflakes`

gwsumm/tabs/sei.py
This PR fixes a bug introduced by #115.
=> Fixed bug in SEIWatchDogTab.write_html

bin/gw_summary, gwsumm/html/bootstrap/__init__.py, gwsumm/tabs/core.py
This PR fixes some minor bugs in cross-linking to other summary page instances, mainly in preserving alphabetical ordering.
=> Fixed minor bugs in cross-linking

gwsumm/data/mathutils.py, gwsumm/triggers.py
This PR adds support for reading HACR triggers into summary pages for GEO600. I also fixed a bug in parsing math when using GEO channels that don't follow the LIGO channel naming convention.
=> Added support for HACR trigger generator

gwsumm/html/__init__.py, gwsumm/html/bootstrap.py, gwsumm/html/static.py, gwsumm/html/tables.py, gwsumm/tabs/data.py, gwsumm/tabs/etg.py, gwsumm/tabs/guardian.py, gwsumm/tabs/hveto.py, gwsumm/tabs/ihope.py, gwsumm/tabs/management.py, gwsumm/tabs/sei.py
This PR does a few things in a single commit (sorry)
- separated `html.__init__` into modules
- renamed `data_table` function to just `table`
- added support for table captions
- use captions in all `html.table` calls
=> Improved HTML <table> displays

gwsumm/html/tables.py, gwsumm/tabs/data.py, gwsumm/tabs/etg.py, gwsumm/tabs/management.py
This PR improves the HTML display of a few tabs, mainly by use of the `<samp></samp>` tag for channel and flag names.
=> Minor changes to HTML content for a few tabs

share/js/gwsumm.js
Uses fancybox title helper to anchor image captions inside of pop up image boxes.
=> Anchored captions inside of fancybox windows

gwsumm/archive.py, gwsumm/tests/test_archive.py, gwsumm/triggers.py
This PR improves the archival of event tables, including unit tests.
=> Improve table archiving and unit tests

gwsumm/data/timeseries.py
This PR modifies `gwsumm.data.timeseries.find_frames` to use the most recent frame returned by datafind to interpolate the paths of more recent frame files that aren't in the database yet. This should reduce latency on any data outputs.
=> Interpolate GWF file paths beyond what datafind returns

gwsumm/data/mathutils.py
This PR modifies the `mathutils` module to handle ratios of spectrograms that differ only in the upper-frequency cutoff, if `f0` and `df` match.
=> Allow shape mismatch in spectrogram ratio

gwsumm/tabs/management.py
This PR modifies the `AccountingTab` to support multiple states.
=> Added support for states in AccountingTab

gwsumm/plot/__init__.py, gwsumm/plot/core.py, gwsumm/plot/triggers.py
This PR updates plot styling for matplotlib 2, pending changes to gwpy's default plot formatting that will become available in gwpy 0.5.
=> Updating plot styling for matplotlib 2

bin/gw_summary, gwsumm/data/timeseries.py, gwsumm/triggers.py, requirements.txt, setup.py
This PR updates this package against the backwards-incompatible changes introduced by gwpy-0.5.
=> Updated gwpy usage to 0.5

gwsumm/data/timeseries.py
This PR modifies the low-level `_get_timeseries_dict` method to use channel names (`str`) as keys in the internal `dict`s, rather than `Channel` objects, since if these get modified the hash changes, meaning key mapping breaks.
This should fix the problem with preserving the `dtype` configuration option (and others) across multiple segment reads.
=> Use channel names as dict keys in get_timeseries

gwsumm/data/coherence.py, gwsumm/data/spectral.py, gwsumm/data/timeseries.py, gwsumm/plot/segments.py
This PR brings a couple of codes up-to-date with upstream changes in gwpy-0.5.
=> Updates for GWpy 0.5

gwsumm/archive.py, gwsumm/tests/test_archive.py, gwsumm/triggers.py
This PR hopes to improve, in general, the layout of the module code, including inline and online documentation, and the test suite.
=> Improvements to documentation, layout, and tests

bin/gw_summary, bin/gwsumm-plot-guardian, bin/gwsumm-plot-triggers, gwsumm/archive.py, gwsumm/channels.py, gwsumm/config.py, gwsumm/data/timeseries.py, gwsumm/plot/__init__.py, gwsumm/plot/builtin.py, gwsumm/plot/core.py, gwsumm/plot/guardian.py, gwsumm/plot/mixins.py, gwsumm/plot/noisebudget.py, gwsumm/plot/range.py, gwsumm/plot/segments.py, gwsumm/plot/sei.py, gwsumm/plot/triggers.py, gwsumm/plot/utils.py, gwsumm/tabs/etg.py, gwsumm/tabs/guardian.py, gwsumm/tabs/management.py, gwsumm/tabs/sei.py, gwsumm/tests/test_archive.py, gwsumm/tests/test_channels.py, gwsumm/tests/test_plot.py, gwsumm/triggers.py, gwsumm/units.py, setup.py
This PR represents a large refactoring of this package to use `gwpy.plot` as the plotting engine. Included are a large number of other bug fixes and refactors.
=> Update to use gwpy.plot module

gwsumm/channels.py, gwsumm/plot/builtin.py, requirements.txt
This PR fixes a couple of bugs that present when no data are available, mainly due to `min([])` errors, and the like.
=> Fixed bugs when no data are available

gwsumm/tabs/etg.py
This is an emergency fix following #207.
=> Forgot to remove one reference to trigfilt

gwsumm/plot/builtin.py
This PR patches `SpectrumDataPlot.draw` to handle errors from performing math on an empty dataset.
=> Added protection against empty data when plotting spectra

gwsumm/data/timeseries.py
This PR adds logic that uses `gwpy.io.gwf.data_segments` (see gwpy/gwpy#1070) to filter out segments that don't contain Virgo's h(t) channels.
=> Handle gaps in Virgo h(t) channels

requirements.txt
=> Require ligo-gracedb >= 2.0.0

gwsumm/tabs/gracedb.py
This PR fixes some issues in the parsing of superevents.
=> Fixed parsing of superevents

gwsumm/tabs/gracedb.py
This PR updates the logic for parsing gracedb event labels into a 'context' for the event. The logic is now as follows:
- if any of the 'bad' labels are present, use 'danger'
- if the INJ label is present, use 'warning'
- if _all_ of the 'good' labels are present, use 'success'
An example is [here](https://ldas-jobs.ligo-la.caltech.edu/~duncan.macleod/summary/testing/gracedb-labels/1235433618-1238112018/analysis/gw_events/) [LIGO.ORG].
=> Updated gracedb label context

.travis.yml, bin/gw_summary_pipe, gwsumm/data/coherence.py, gwsumm/data/mathutils.py, gwsumm/data/spectral.py, gwsumm/plot/segments.py, gwsumm/plot/sei.py, gwsumm/plot/triggers.py, gwsumm/tabs/core.py, gwsumm/tabs/fscan.py, gwsumm/tabs/gracedb.py, gwsumm/tabs/guardian.py, gwsumm/tabs/management.py, gwsumm/tests/test_channels.py, requirements.txt
This PR implements a few more python3-related fixes.
=> More python3 fixes

gwsumm/plot/range.py
This PR implements a simple algorithm to estimate the cumulative time-volume searched by a network of GW detectors:
1. Construct a `SegmentList` of coincident observing segments that is active whenever at least two detectors are in observing mode
2. Construct an "effective network range" equal to the BNS range of the second-most sensitive detector at any given time
3. Compute the VT based on this segment list and range
Test output is available [**here**](https://ldas-jobs.ligo.caltech.edu/~alexander.urban/summary/ER14-test/1238166018-1238770818/range/) (requires `LIGO.ORG` credentials). Note, this comes by a request from LIGO Lab management, who want to deliver a figure-of-merit to the U.S. National Science Foundation.
=> Support combined time-volume estimates

gwsumm/plot/triggers.py, gwsumm/segments.py
This PR allows users to read segments out of HDF5 files by configuring a `segments-hdf5-path` in the `DEFAULT` INI section.
=> Support reading segments from HDF5 files

gwsumm/html/static.py, gwsumm/html/tests/test_static.py, setup.py
This PR fixes a couple of bugs related to JS minification (during setup.py builds) and the jQuery version pin.
=> Fix JS minification and jQuery version pin

gwsumm/html/bootstrap.py, gwsumm/html/html5.py, gwsumm/html/static.py, gwsumm/html/tests/test_bootstrap.py, gwsumm/html/tests/test_html5.py, gwsumm/html/tests/test_static.py, gwsumm/tabs/builtin.py, gwsumm/tabs/core.py, gwsumm/tabs/data.py, gwsumm/tabs/etg.py, gwsumm/tabs/fscan.py, gwsumm/tabs/gracedb.py, gwsumm/tabs/guardian.py, gwsumm/tabs/management.py, gwsumm/tabs/misc.py, gwsumm/tabs/sei.py, gwsumm/tabs/stamp.py, gwsumm/tests/test_data.py, requirements.txt, setup.py
This PR includes a number of enhancements for an upgrade to bootstrap-4, and bumps the gwpy version pin to 1.0.0.
=> Migrate to bootstrap-4 and gwpy-1.0.0

gwsumm/tabs/core.py
This PR implements a bugfix for a (really foolish) problem that arises when a calendar is requested in GPS mode.
=> Bugfix for GPS mode navbar text

setup.py
This PR implements some metadata updates in anticipation of a 1.0.1 release.
=> Some metadata updates

gwsumm/__main__.py, gwsumm/batch.py, gwsumm/tests/test_batch.py, setup.cfg
This PR implements unit testing for the `gwsumm.batch` command-line module.
=> Implement unit tests for gwsumm.batch

.travis.yml, gwsumm/__main__.py, gwsumm/html/static.py, gwsumm/html/tests/test_static.py, gwsumm/tabs/misc.py, requirements.txt, setup.cfg
This PR requires gwdetchar-2.0.0 as well as a number of CSS+JS security upgrades.
=> Require gwdetchar-2.0.0 and upgrade CSS+JS libraries

.readthedocs.yml, docs/requirements.txt, setup.cfg
This PR fixes (attempts to fix) the broken readthedocs builds.
=> Update RTD config

gwsumm/data/coherence.py, gwsumm/state/core.py, gwsumm/tabs/stamp.py
=> Fix flake8 failures with new flake8

gwsumm/plot/sei.py
Uses this helpful migration note: https://gwdatafind.readthedocs.io/en/stable/migrating/#simplified-single-calls
=> Change from glue.datafind to use gwdatafind

gwsumm/plot/utils.py
This PR introduces the `density` matplotlib property to GWSumm.
=> Add density option for histograms

gwsumm/triggers.py
This PR adds functionality to `get_triggers` so that when parameters like `tstart` and `tend` are requested to be extracted from omicron trigger files (but not `duration`), the `duration` column will be computed and added to the trigger table. This also works when `fstart` and `fend` are requested (but not `bandwidth` or `central_freq`), then `bandwidth` and/or `central_freq` will be computed and added to the table.
Together with updated configuration files, https://git.ligo.org/detchar/ligo-summary-pages/-/merge_requests/395, we can see the updated version of the glitches page here: https://ldas-jobs.ligo-wa.caltech.edu/~evan.goetz/summary/day/20240101/lock/glitches/
Compare to the original page: https://ldas-jobs.ligo-wa.caltech.edu/~detchar/summary/day/20240101/lock/glitches/
The only …
=> Extend triggers information when possible

gwsumm/html/static.py, pyproject.toml
Update gwbootstrap to the latest version to handle fancybox API changes
=> Bump gwbootstrap version

gwsumm/archive.py
This PR adds better docstrings and code comments to archive.py
=> Add better commenting and docstrings to gwsumm/archive.py

gwsumm/channels.py
This PR adds better docstrings and code comments to channels.py
=> Add better commenting and docstrings to gwsumm/channels.py

gwsumm/html/bootstrap.py, gwsumm/html/static.py, pyproject.toml
`gwbootstrap` will be updated to version 1.3.5 to fix a bug in the dropdown alignment. This PR updates the pin and updates a code comment
=> Use gwbootstrap 1.3.5

gwsumm/html/static.py, pyproject.toml
This PR updates the gwdetchar and gwbootstrap version pins to the latest release
=> Update gwbootstrap version pins
