- gwsumm/data.py
This PR fixes a corner-case failure mode whereby meta-channel timeseries/spectrograms for which different channels have different availability (segments) would fail.
The code introduced here uses the intersection of the available data for all channels to ensure every channel has some data on which to operate.
> Fix meta-channel timeseries/spectrograms with mismatched segments

- gwsumm/data.py
- gwsumm/plot/builtin.py
- gwsumm/plot/core.py
- gwsumm/plot/mixins.py
- gwsumm/tabs/__init__.py
- gwsumm/tabs/data.py
- gwsumm/tabs/management.py
This PR implements a custom tab for displaying the time accounting data recorded by the `ODC-OBSERVATORY_MODE` channel.
The main additions are
- `/gwsumm/tabs/management.py` - defining the new tab
- `gwsumm/plot/builtin.py:SegmentPiePlot` - new plot for pie charts from segments
> New time accounting tab

- gwsumm/tabs/data.py
This PR introduces a new `no_plots` property for the `DataTab`. This is used to configure a tab to read some data in a particular state, but not actually render any figures.
This is used in the multi-interferometer pages to read data for H1/L1 channel in IFO-specific states, but make plots with both data sets.
> New no_plots attribute for DataTab

- gwsumm/state/core.py
- gwsumm/tabs/__init__.py
- gwsumm/tabs/etg.py
- gwsumm/triggers.py
This PR introduces a new `EventTriggerTab`, providing a generic interface to the daily CBC-style tabs with plots and tables of loudest events. Tested with Daily CBC BNS and Omicron glitches.
Two minor, backwards-compatible changes were required and are included in the preceding commits.
> New EventTriggerTab

- bin/gw_summary
This PR enables HDF archiving for the GPS mode, via the same `--archive` option as used for calendar modes.
> Added archive option for GPS mode

- bin/gw_summary
- gwsumm/channels.py
- gwsumm/globalv.py
- gwsumm/html/bootstrap/__init__.py
- gwsumm/tabs/builtin.py
- gwsumm/tabs/core.py
- gwsumm/tabs/guardian.py
- gwsumm/tabs/hveto.py
- gwsumm/tabs/ihope.py
- gwsumm/tabs/management.py
- gwsumm/tabs/sei.py
This PR introduces a custom 404 tab for page not found. Changes are as follows
- `gw_summary` now writes a `404.html` page in the base of the output directory and an associated `.htaccess` file that disables directory listing and redirects 403 errors to 404
- the `Tab.base` attribute was renamed to `Tab.path`
- `Tab.write_html` now accepts a `base` keyword argument that it passes onto `Tab.initialize_html_page`
- a few other minor bug fixes
The LDAS admins have enabled override of the `Indexes` option in apache (`httpd`) to enable this for the LIGO summary pages.
> New 404 error tab

- gwsumm/tabs/hveto.py
This PR changes the processing of the hveto directories to break the symbolic link before doing any processing. This means no symbolic links will be used in the output HTML.
@areeda: is this what you were after?
> HvetoTab: resolve symlink before analysis

- gwsumm/plot/__init__.py
- gwsumm/plot/builtin.py
- gwsumm/plot/triggers.py
This PR updates the default colormaps for image-like plots (include event scatters), and sets the default for matplotlib >= 1.5 to the new 'viridis' default.
This closes #20 by enabling the sequential colormaps as early as possible.
This should ideally be installed alongside gwpy/gwpy#173.
> Update colormaps for matplotlib 1.5

- gwsumm/plot/builtin.py
- gwsumm/plot/core.py
- gwsumm/plot/triggers.py
- gwsumm/tabs/builtin.py
This PR adds minimal support of PDF images, by adding `rasterized` to the list of understood plotting kwargs, and rendering both png and pdf images when PDF is requested, as follows:
- display png in HTML scaffold
- link png image to pdf image
> Support pdf images

- gwsumm/tabs/data.py
- gwsumm/tabs/etg.py
This PR modifies the `DataTab.process_state` logic to catch any and all exceptions coming from `Plot.process` operations under multi-processing and raise them when the plotting is done.
Currently the exceptions are hidden away by the multiprocessing, which is probably not great.
> Raise all plot exceptions

- gwsumm/data.py
I have fixed a bug(/feature) in `gwsumm.data._make_key` whereby the same FFT params seem to be accessed at different stages as `int` or `float`, making the key different in the two cases.
The fix forces the conversion to `float` making the key `str`.
Additionally I commited a small enhancement to copy the general `fftparams` values to each channel if they don't have overrides - this should mean that if the general `fftparams` aren't passed later on, the channel will already have the values so the outcome should be the same.
> Fixed bug in fftparams usage in `data._make_key`

- gwsumm/data.py
- gwsumm/plot/builtin.py
- gwsumm/plot/core.py
- gwsumm/tabs/builtin.py
- gwsumm/tabs/data.py
- gwsumm/tests/compat.py
- gwsumm/tests/test_archive.py
- gwsumm/tests/test_channels.py
- gwsumm/tests/test_data.py
- gwsumm/tests/test_mode.py
- gwsumm/tests/test_plot.py
- gwsumm/tests/test_tabs.py
This PR fixes #39 by implementing a `defaultstate` property for the `StateTab` class. This is automagically set to the first state unless one of the states is added with `default=True` either in the call to `Tab.add_state` or by using a trailing asterisk in the config file, e.g.
```ini
[tab-hoft]
states = Locked, Ready*, Observing
```
> Denote default state by trailing asterisk

- gwsumm/config.py
This PR fixes a bug in the `load_units` method where it tries to zip-separate something that doesn't want to be unzipped.
> Bug fix in Config.load_units

- gwsumm/tabs/etg.py
This PR enables the use of the `foreword` config option when creating an `EventTriggerTab`.
> Added support for foreword in EventTriggerTab

- gwsumm/data.py
This PR fixes a problem when working out which new timeseries data are needed to complete a spectrogram request.
@paulaltin introduced a new fancy key structure in #33 that didn't get pushed up to this bit of code.
> Fixed keys for spectrogram/timeseries check

- gwsumm/tabs/__init__.py
- gwsumm/tabs/gracedb.py
Just queries gracedb for some events, then builds a table of events with some columns and a sorting.
Future developments might include a segment-style plot showing when the events occurred relative to the state segments.
> GraceDbTab: new tab for summarising gracedb entries

- gwsumm/tabs/builtin.py
- gwsumm/tabs/fscan.py
This commit adds the `img-responsive` bootstrap class for all `<img>` elements
> Use img-responsive class for imgs

- gwsumm/plot/segments.py
This PR fixes a bug in `gwsumm.plot.segments` - just a type problem when using the `pylal.xlal.types.ligotimegps.LIGOTimeGPS` object.
> Fixed bug in summing LIGOTimeGPS and numpy.int64

- gwsumm/triggers.py
This PR adds a `try/except` block to `get_triggers` to catch the `ValueError` raised by `trigfind.find_detchar_files` if the channel-level directory doesn't exist. For the summary pages, we just want a warning and an empty plot.
> Catch ValueError from trigfind

- gwsumm/data.py
This PR fixes a bug where archived spectrograms weren't being recognised by `get_spectrograms`.
> Fixed bug in archive keys for get_spectrograms

- gwsumm/config.py
- gwsumm/html/__init__.py
- gwsumm/html/bootstrap/__init__.py
- gwsumm/tabs/builtin.py
- gwsumm/tabs/core.py
- gwsumm/tabs/data.py
- share/sass/gwsumm.scss
This PR improves the HTML and CSS styling for the `navbar`, and related elements on the page. The main changes are
- only write a single copy of the navbar, and just responsively style it well
- embed the whole page between the `</header>`and `<footer>` inside a single `.container`
- improved responsive styling of navbar elements
> Improved HTML for navbar and friends

- gwsumm/plot/mixins.py
- gwsumm/plot/segments.py
- requirements.txt
- setup.py
Turns out the standard library `xml` module doesn't write an SVG that works with javascript, so this PR reverts the commit that removed `lxml`. Also, I fixed a `TypeError` in segment plotting when trying to combine `glue.lal.LIGOTimeGPS` with `numpy.int64`.
> Revert removal of lxml, and fixed a bug

- bin/gw_summary
This PR adds a `--no-htaccess` command-line option to `gw_summary` to disable writing the `.htaccess` file and custom HTTP error pages. This breaks everything on systems where custom `.htaccess` files are not allowed under the apache configuration, e.g. atlas.
> Added gw_summary option to skip writing .htaccess

- bin/gw_summary
This PR adds a `-j` short form of the `--multi-process` option to `gw_summary`, analogous to that from GNU `make`.
> Added '-j' short form of '--multi-process' for gw_summary

- gwsumm/utils.py
This PR fixes the references to ATLAS (AEI-Hannover) in `gwsumm.utils.get_default_ifo`, meaning the G1 (GEO-600) interferometer prefix should be automatically selected correctly.
> Fixed atlas cluster FQDN checks for default IFO

- bin/gwsumm-plot-guardian
This PR simplifies the plotting in the `gwsumm-plot-guardian` executable, which only requires a single plot to be generated. The trick is to just reset the `tab.plots` immediately after creation to just contain the first plot, then we don't need to delete them after the fact.
This also means we don't have to worry about plots not being generated because of multiprocessing weirdness.
> Simplified plot hacks in gwsumm-plot-guardian

- docs/configuration/data.rst
- gwsumm/data.py
This PR introduces an optional syntax for providing a `match` string for datafind queries. Users can now give `frametype = <type>|<match>` to query for frames of type `<type>` whose paths contain `<match>`, e.g. `frametype = T|RDS9` for GEO.
> Added parsing for datafind name matching

- gwsumm/config.py
- gwsumm/data.py
This PR fixes problems with configuring time-domain filters via `lambda` expressions in the configuration file. It turns out `numpy` and `math` need to be available when the lambda is evaluated, not when it is used, plus there was a problem with units meaning astropy would refuse to use some functions.
> Fixed bugs in using lambda filter expression

- bin/gw_summary
- gwsumm/config.py
- gwsumm/plot/builtin.py
- gwsumm/plot/core.py
- gwsumm/plot/mixins.py
- gwsumm/plot/range.py
- gwsumm/plot/segments.py
- gwsumm/plot/triggers.py
- gwsumm/tabs/data.py
This PR  introduces parsing of an `[rcParams]` configuration section to set global `matplotlib.rcParams`, and also plot-level configuration options for context-managed rcParams for each plot.
> Allow custom rcParams globally and per-plot

- gwsumm/data.py
This PR fixes the use of the `median` operation in calculating the averaged coherence spectrum from the component spectrograms. The trick is to calculate the median of the real and imaginary parts of the CSD separately, then sum them.
> Fixed calculation of median coherence

- bin/gw_summary_pipe
- gwsumm/config.py
- gwsumm/tests/test_config.py
This PR fixes two problems in running `gw_summary` and `gw_summary_pipe` without passing a `defaults.ini` file, or at least one without an `[html]` section.
> Fixed a couple of bugs in running gw_summary{_pipe} without defaults.ini

- gwsumm/data/spectral.py
- gwsumm/plot/builtin.py
This PR fixes #81 by allowing the `ratio` parameter for a spectrogram to point to a file on disk containing a reference spectrogram against which to normalise the data. This is used by GEO and was supported already in previous summary page incarnations.
In the mean time I fixed a bug in calculating rayleigh spectrograms using the `format` argument, and not `method`.
> Added support for fixed-reference spectrogram normalisation

- gwsumm/data/spectral.py
This PR fixes two bugs in `data.spectral`:
- need to import common `math`/`numpy` stuff for `eval(filter)` calls
- gwpy 0.1 introduced overlapping time strides in spectrogram, meaning the amount of data in each time bin is greater, so we need to account for that in how we truncate the timeseries used to calculate a spectrogram
> Fixed two bugs in `data.spectral`

- .travis.yml
This PR moves the python-2.6 build to the allowed failures column, reducing support for that version to best-effort.
> Reduce python-2.6 support to best-effort

- gwsumm/channels.py
This PR works around a problem with meta-channels (mathematical combinations of real channels) raising an 'ambigious channel request' error, by shortcutting to the first channel if the parameters of all matches seem to be the same.
> Work around ambiguous channel bug for math meta-channels

- gwsumm/plot/builtin.py
- gwsumm/plot/core.py
- gwsumm/plot/triggers.py
- gwsumm/tabs/data.py
- gwsumm/tabs/etg.py
- gwsumm/tests/test_config.py
- gwsumm/triggers.py
- requirements.txt
This PR modifies the `gwsumm.triggers` module and all callers to use the `GWRecArray` object as the internal storage for triggers, rather than a `LIGO_LW` table (`glue.ligolw.table.Table`).
> Use recarray for trigger storage

- gwsumm/archive.py
- gwsumm/tests/common.py
- gwsumm/tests/test_archive.py
- gwsumm/tests/test_channels.py
- gwsumm/tests/test_config.py
- gwsumm/tests/test_data.py
- gwsumm/tests/test_mode.py
- gwsumm/tests/test_plot.py
- gwsumm/tests/test_tabs.py
- gwsumm/triggers.py
This PR introduces trigger archiving when using the `--archive` command-line option. Previously this was a pain because of the LIGO_LW table formatting, but with `GWRecArray` things are a bit easier.
Each column is stored as its own dataset, with the `segments` attribute as another dataset, with a fixed GPS offset to preserve nanosecond precision.
> Added trigger archiving

- gwsumm/segments.py
This PR updates error handling in `get_segments` to use the new `IORegistryError` introduced in astropy 1.2.
This doesn't introduce a hard dependency on astropy >= 1.2, but we should move to that as soon as python 2.6 is dead.
> Updated segment read error to use astropy 1.2 exceptions

- gwsumm/plot/builtin.py
- gwsumm/tabs/core.py
This PR introduces a new syntax and functionality to undo demodulation, by fudging the frequency index back to the original pre-demodulation values. The user can give the demodulation frequency in the `[channel]` configuration:
```ini
[channel]
demodulation = 1028
```
Additionally, if the desired frequency-range on the plot is below the demodulation frequency, it is assumed that the information at those frequencies have been mapped into 'negative' frequencies in the new demodulated channel, so the appropriate conversions are done to reverse the frequencies so the data are in the right order.
This is originally to support the displaying the demodulated channels used for studying parametric instability in LIGO.
> New functionality and syntax for undoing demodulation

- gwsumm/data/spectral.py
- gwsumm/tabs/data.py
This PR fixes a problem in selecting the 'rayleigh' spectrum, where that selection would get wiped out if the channel had already been calculated via a median-mean spectrum (or otherwise).
> Fix bugs in handling of Rayleigh method selection

- gwsumm/utils.py
This PR fixes a shortcoming of the `safe_eval` function, which needs to have module-level access to `numpy` and `pi` so that users can use those in their expressions.
> Added imports for use in safe_eval

- bin/gw_summary_pipe
This PR adds the `--no-htaccess` option to `gw_summary_pipe`, which gets passed to all calls of `gw_summary` in the output DAG.
This is mainly to support summary pages for GEO-600 where the ATLAS web server doesn't support custom .htaccess.
> Added --no-htaccess option to gw_summary_pipe

- gwsumm/plot/builtin.py
mpl breaks readily on empty data when 'weights' are present, so need to handle that special case whilst making sure that the plot looks good. This PR cleans up the code to handle histogram errors.
> Improved handling of empty histograms

- gwsumm/plot/segments.py
Since #74 each plot is `draw()`n in an rcParams context, meaning any changes made inside that method are not kept once the function closes. This PR simplifies the customisation of the `labelsize` for the `StateVectorDataPlot` to take advantage of this.
> Simplify custom labelsize in StateVector plotting

- gwsumm/data/coherence.py
- gwsumm/data/spectral.py
- gwsumm/plot/builtin.py
- gwsumm/plot/triggers.py
This PR removes all remaining references to the deprecated (now removed) `gwpy.spectrum.Spectrum` object.
> Removed references to GWpy's deprecated Spectrum

- gwsumm/archive.py
- gwsumm/plot/core.py
- gwsumm/plot/triggers.py
- gwsumm/tests/test_utils.py
- gwsumm/utils.py
This PR fixes the handling of `weights` in the `TriggerHistogramDataPlot` class. This required improving the `safe_eval` method to handle `globals` and `locals` parameters.
> Fixed handling of weights in trigger histogram

- gwsumm/utils.py
This PR improves the regex that is used to catch `os.` strings in inputs to `safe_eval`.
> Improved handling of os. strings in utils.safe_eval

- gwsumm/data/timeseries.py
This PR implements a check against the availability of `X1_HOFT_C00` frames, moving to `X1_DMT_C00` if gaps are present. In most circumstances this should allow lower-latency access to h(t) - if no extra frame files are found, the original type is used for consistency.
> Use X1_DMT_C00 for lower-latency access to h(t)

- gwsumm/tabs/sei.py
This PR modifies the `gwsumm.tabs.sei.SEIWatchDogTab.write_html` method to include those trips with an 'unknown' cause in the summary table.
> Include 'unknown' causes in SEIWatchDogTab table

- bin/gw_summary
- gwsumm/archive.py
- gwsumm/channels.py
- gwsumm/html/bootstrap/__init__.py
- gwsumm/mode.py
- gwsumm/plot/builtin.py
- gwsumm/plot/segments.py
- gwsumm/tabs/core.py
- gwsumm/tabs/data.py
- gwsumm/tabs/etg.py
- gwsumm/tabs/fscan.py
- gwsumm/tabs/hveto.py
- gwsumm/tabs/ihope.py
- gwsumm/tabs/stamp.py
- gwsumm/tests/test_mode.py
- requirements.txt
- setup.py
This PR introduces a re-write of the `gwsumm.mode` module, using the `enum.Enum` class introduced in python3 and back-ported by python2.7 via [`enum34`](https://pypi.python.org/pypi/enum34/).
> Re-written mode module with enum

- gwsumm/triggers.py
This PR does two things
- modularises `triggers.get_triggers` so that reading events from a single-file cache is much more efficient
- sorts events in `triggers.keep_in_segments` so that the filtering actually works (fixes #102)
> Sort triggers before filtering for time segments

- share/js/gwsumm.js
This PR fixes a problem with setting the page state based on the `location.hash`.
> Fixed some variable assignment bugs in gwsumm.js

- gwsumm/data/mathutils.py
- gwsumm/tests/test_data.py
This PR modifies the `data.mathutils` module to support an arbitrary number of _non-commutative_ mathematical operations attached to a channel name, e.g.
```
L:PSL-ISS_DIFFRACTION_AVG.mean,m-trend * 0.02 + 0.385
```
All mathematic operations are performed simply left-to-right, meaning, 
```
L1:PSL-ISS_DIFFRACTION_AVG.mean,m-trend + 0.1  * 0.2
```
is logically the same as
```
(L1:PSL-ISS_DIFFRACTION_AVG.mean,m-trend + 0.1)  * 0.2
```
and not 
```
L1:PSL-ISS_DIFFRACTION_AVG.mean,m-trend + (0.1  * 0.2)
```
as would be assumed in written maths.
> Support more complicated maths

- bin/gw_summary
- gwsumm/plot/core.py
- gwsumm/tabs/builtin.py
Added a new tab class that is a direct link to a specified URL using the `tab.href` property of the tab. One line in `gw_summary` was modified that tells the tablist processor to skip link tabs when it makes directories and writes HTML. It can be done without using the ArchivedUrlTab class by setting `type = 'archived-link'`, but that seemed a little hacky.
Config file example:
```
[tab-gwpy]
type = link
name = GWpy
url = https://github.com/gwpy
```
Output example:
`https://ldas-jobs.ligo.caltech.edu/~thomas.massinger/summary/test_buttons3/day/20151226/instrument_status/`
Fixes #105
> Added tabs that link to external URLs

- gwsumm/plot/core.py
- gwsumm/tabs/builtin.py
Adds functionality to add captions to figures in PlotTab class pages. 
Each plot is contained in a `SummaryPlot` class object, which contains the URL to the image and writes the `fancybox plot` class HTML. The caption tag needs to be passed to this same line of HTML, so I wrote it to be an instance variable of the `SummaryPlot` class. 
After the PlotTab class parses the config file for images, I added a block of code to make a list of captions that mirrors the ordering of the list of plots. If a plot doesn't have a caption, an entry of `caption = ''` is generated to keep the lists the same size with correct ordering. The lists `plots` and `captions` are both stored in the kwargs dictionary used to initialize the PlotTab. 
When each plot contained in the PlotTab is initialized in the …
> Added functionality to read captions from config files

- gwsumm/tabs/data.py
This PR modifies the 'Segment Information' sections for the `DataTab` to write segments from the 'All' state, not just those relevant to the given state. This should prevent confusion over which segments are which.
> Include all segments in Segment Information sections

- gwsumm/plot/builtin.py
- gwsumm/plot/range.py
- gwsumm/plot/segments.py
- gwsumm/plot/triggers.py
This PR modifies the `gwsumm.plot` module to not show a state segments bar along the bottom of a time-axis plot if the state is 'All', i.e. showing all data. This bar is totally unnecessary.
> Don't show state bar for 'All' state

- bin/gw_summary
- gwsumm/config.py
- gwsumm/utils.py
This PR modifies the `GWSummConfigParser` class to add a `set_ifo_options` method to set the following default options
- `IFO`
- `ifo`
- `SITE`
- `site`
- `observatory`
See the docstring for the method for details.
> Added more observatory-related configuration defaults

- gwsumm/config.py
- gwsumm/data/coherence.py
- gwsumm/data/spectral.py
- gwsumm/html/bootstrap.py
- gwsumm/html/html5.py
- gwsumm/plot/builtin.py
- gwsumm/plot/core.py
- gwsumm/plot/range.py
- gwsumm/plot/registry.py
- gwsumm/plot/segments.py
- gwsumm/plot/triggers.py
- gwsumm/segments.py
- gwsumm/tabs/builtin.py
- gwsumm/tabs/core.py
- gwsumm/tabs/etg.py
- gwsumm/tabs/fscan.py
- gwsumm/tabs/guardian.py
- gwsumm/tabs/hveto.py
- gwsumm/tabs/stamp.py
- gwsumm/triggers.py
- gwsumm/utils.py
This PR updates all `isinstance(..., str)` calls to use `six.string_types`.
> Use six.string_types for all isinstance calls

- gwsumm/tabs/data.py
- gwsumm/tabs/etg.py
- gwsumm/triggers.py
This allows the optional setting of a trigger-filter string in the config file which is used to remove some triggers for display. You can use anything that is a column in the data table. For example the following
trigger-filter = template_duration > 0.7    template_duration < 500 
produces
https://ldas-jobs.ligo-wa.caltech.edu/~ahnitz/gwpysoft/L1/day/20161130/detchar/pycbc_live/
The arguments are processed left to right.
> allow a trigger filter option

- gwsumm/data/mathutils.py
This PR fixes a potential bug when combining channel data - sometimes two channels returned from `get_timeseries` or similar will return with different shapes, because of different data availability, so we need to use the intersection of the spans.
> Fix corner-case bug in combining data with mathutils

- gwsumm/tabs/management.py
This PR modifies the way that group segments are calculated for the `AccountingTab`, allowing for sub-states to be excluded from the overall results (by virtue of not being included in the configuration in the first place).
> Reworked group state segment generation on AccountingTab

- gwsumm/state/core.py
- gwsumm/tabs/data.py
- gwsumm/tabs/etg.py
This PR modifies the `DataTab.write_state_html` method to print a `State Information` section, including the defintion and segments for the state of a given page.
> Added 'State Information' section to HTML output of DataTab

- .travis.yml
- .travis/build-src-dependencies.sh
- setup.cfg
This PR updates the travis-ci build-and-test configuration as follows:
- added LAL build
- replaced LDAS_TOOLS with LALFrame build
- improved configuration with build/env matrix
- added coverage configuration to `setup.cfg`
> Updated build-and-test configuration

- gwsumm/plot/triggers.py
- gwsumm/tabs/data.py
- gwsumm/tabs/etg.py
- gwsumm/triggers.py
This PR improves the event filtering options to apply the filter on the `get` operation, not the `read`, so that two tabs can use the same dataset with different filtering.
This renames the configuration option for the `EventTriggerTab` to `event-filter`.
This closes #138 (supersedes).
> Filter events on `get` op, not `read`

- gwsumm/triggers.py
This PR modifies `triggers.get_triggers` to parse any options in the `[etg]` configuration section prefixed with `trigfind-` and pass them directly to `trigfind.find_trigger_files`, e.g. ``trigfind-base``.
> Added parsing of keyword arguments to pass to trigfind

- gwsumm/tabs/guardian.py
This PR implements states for `GuardianTabs`. The change is made backwards compatible by not including the state name in the plot tag for plots in the 'All' state.
> Added states for GuardianTabs

- gwsumm/segments.py
This PR modifies `get_segments` to not force the `known` segments for components of a compound flag on everything, and to just let DataQualityFlag handle the mathematical compounding of multiple flags.
> Don't force known segments on everything in get_segments

- gwsumm/data/spectral.py
- gwsumm/io.py
- gwsumm/plot/builtin.py
This PR adds support for passing a `frequency-response` filter as a filepath containing a transfer function measurement.
> Added support for frequency-response files

- .travis.yml
- docs/install.rst
- requirements.txt
- setup.py
This PR updates the build/install infrastructure to reference the [`lscsoft-glue`](https://pypi.python.org/pypi/lscsoft-glue/) and [`dqsegdb`](https://pypi.python.org/pypi/dqsegdb/) packages on pypi.
> Updated dependencies to references lscsoft-glue and dqsegdb on pypi

- gwsumm/html/bootstrap.py
This PR modifies `gwsumm.html.bootstrap` to use `pip.get_installed_distributions` to produce a complete package listing that is printed to a new _Package List_ section of the _About_ page.
> Added package listing to About tab

- gwsumm/plot/__init__.py
- gwsumm/plot/noisebudget.py
This PR adds the `gwsumm.plot.noisebudget`, defining two new plots:
- `'noise-budget'`, subclass of `'spectrum'` plot where first channel is presumed as _h(t)_, and all others are summed using a quadsum to make a noise budget
- `'noise-budget-ratio'`, similar to above but the sum of noises is divided by the _h(t)_ spectrum to show gaps in the noise budget
> Added new module for noisebudget plots

- gwsumm/plot/builtin.py
- gwsumm/plot/core.py
This PR improves the way state segment Axes are configured, including the addition of a new plot configuration option `no-state-segments` which if set to `True` will force the `TimeSeriesDataPlot.add_state_segments` method to use `visible=False`.
The motivation for this is to hide the state segments bar on those plots where the state is a fake, allowing data from the 'locked' or 'observing' states for each interferometer to be shown together, for example.
> Added plot configuration option to hide state segments Axes

- gwsumm/plot/builtin.py
- gwsumm/plot/range.py
- gwsumm/plot/segments.py
This PR fixes #41 by adding an `axvspan` between GPS 'now' and the end of the plot to indicate that portion of the Axes that exist in the future, so that people don't get confused why the plot is half-empty.
This can be disabled using the `no-future-shade` plot configuration option.
> Added shading of future times in TimeSeriesDataPlots

- .travis.yml
This PR modifies the travis-ci configuration to use the `trusty` ubuntu distributions, which should resolve LAL src build timeouts for py35.
> Use trusty dist for Travis CI builds

- gwsumm/plot/builtin.py
- gwsumm/plot/core.py
- gwsumm/plot/range.py
- gwsumm/plot/segments.py
- gwsumm/plot/triggers.py
This PR implements tight autoscaling for X and Y axes for all plots by default, which is disabled for a given plot/axes if the user specifies a limit (or a bound) for that axis in the configuration.
> Added plot autoscaling

- gwsumm/triggers.py
This PR simplifies some of the (now) unnecessary logic in `gwsumm.triggers.read_cache` now that GWpy provides a generic multiprocessing I/O interface for all file formats.
> Simplified trigger reading in read_cache() method

- .travis.yml
- bin/gwsumm-plot-triggers
This PR adds the two `gwsumm-plot-*` executables to the `script:` portion of the CI build, allowing a simple test that they link properly (i.e. imports work).
> Included gwsumm-plot-* executables in CI tests

- gwsumm/data/timeseries.py
- gwsumm/plot/noisebudget.py
This PR implements automatic calculation for the residual in a noise budget (`quaddiff(darm, sum-of-noises)`).
> Added residuals to noise budget plot

- gwsumm/archive.py
- gwsumm/tests/test_archive.py
This PR fixes some bugs in the testing of the `gwsumm.archive` module
- [a0d8a1d] compare error messages using lower case
- [f9a3433] empty `globalv.SPECTROGRAMS` between tests
The use of the `empty_globalv` is still quicky hacky, and could probably do with being cleaned up, but it works to purpose at the moment.
> Fixed bugs in testing archive module

- gwsumm/tabs/guardian.py
This PR removes the guardian `VERSION` channel check, which simplifies (and speeds up) the processing of guardian data.
**This removes support for guardian core < r1200 (SVN).**
> Removed guardian version check in GuardianTab

- bin/gw_summary
- bin/gwsumm-plot-guardian
- gwsumm/data/coherence.py
- gwsumm/data/range.py
- gwsumm/data/spectral.py
- gwsumm/data/timeseries.py
- gwsumm/state/core.py
- gwsumm/tabs/data.py
- gwsumm/tabs/guardian.py
- gwsumm/tabs/management.py
- gwsumm/tabs/sei.py
- gwsumm/tests/test_data.py
- gwsumm/tests/test_utils.py
- gwsumm/triggers.py
- gwsumm/utils.py
This PR changes `multiprocess={False,True}` to `nproc=1` across the board, bringing the keyword name more in line with gwpy, and setting a standard default of serial processing across the board, which is easier to maintain.
> Renamed multiprocess keyword to nproc everywhere

- gwsumm/triggers.py
This PR improves the parsing and defaults for ETG I/O options, mainly to support the following combination of options
```
etg = cwb
format = cwb.ascii
```
By default the code used to presume `etg='cwb'` always meant the ROOT format, which meant the I/O keywords were getting overloaded with `treename='waveburst'`, which doesn't work when reading the ASCII format.
> Improved parsing of ETG options in gwsumm.triggers

- gwsumm/data/timeseries.py
This PR fixes a `TypeError` when sieve a `Cache` of GWF file paths, because of the mismatch between the two segments libraries in C. This can be removed when `glue.segments` just points at `ligo.segments`
> Cast sieve segment to glue.segments.segment

- gwsumm/archive.py
- gwsumm/channels.py
- gwsumm/data/mathutils.py
- gwsumm/data/spectral.py
- gwsumm/data/timeseries.py
- gwsumm/plot/core.py
- gwsumm/tabs/data.py
- gwsumm/tests/test_channels.py
- gwsumm/tests/test_data.py
This PR implements two updates to channel interactions
- archive the channel list in a table, which means data-based parameters (`sample_rate`, etc) are restored on each run
- link math channels (`X1:TEST * 2`) back to the real channel (`X1:TEST`) so that declared parameters are copied from one to the other.
> Fixed some issues with channels

- gwsumm/channels.py
This PR modifies `gwsumm.channels` to only format CIS URLs for H1 or L1 prefixed channels.
> Only print CIS URLs for H1 or L1 channels

- gwsumm/data/timeseries.py
- gwsumm/state/core.py
- gwsumm/tabs/data.py
This PR fixes issues when trying to use the `--nds` option to `gw_summary`, which pushes the code to use the nds2-client for all data access queries. This is critical for production summary pages for KAGRA.
> Fixed bugs in running in NDS mode

- gwsumm/state/core.py
- gwsumm/tabs/data.py
This PR patches `gwsumm.state` such that, for a given state definition, if `0` will mean 'out-of-state', use `pad=0.` to ride through missing data so we can generate state information. this is extremely useful for KAGRA where we use the state system to find the gaps in the data in the first place.
> Improved access to state data

- gwsumm/tabs/guardian.py
This PR fixes a bug in the `GuardianTab` that has been producing empty `State Transitions` tables for a while.
> Fixed bug in finding guardian state transitions

- gwsumm/data/timeseries.py
- gwsumm/state/core.py
- gwsumm/tabs/data.py
- requirements.txt
- setup.py
This PR upgrades `gwsumm.data` from `glue.datafind` to `gwdatafind` for file discovery. The new package is backwards incompatible with the old one, so this requires a bit of reengineering to handle simple path lists instead of structured URLs.
This might mean, in combination with #193, that we can eliminate the dependence on `lscsoft-glue` altogether, which would be nice. Almost.
> Upgrade to using gwdatafind for URL discovery

- gwsumm/data/mathutils.py
This PR fixes a corner-case failure we have been seeing running the LIGO-Hanford summary pages, when trying to compute the ratio of the calibrated _h(t)_ data, and the front-end-calibrated `CAL-DELTAL_EXTERNAL` data.
These two channels come from different sources, and are stored in different GWF files, with (in general) differing availability (times when GWF files exist). In some situations this can lead to `gwsumm` loading data for a given segment where the spectrogram for one channel has the same time span as the other, but has an offset of a few seconds, because the GWF file boundaries are subtly different. The code would then try to crop both spectrograms to the intersection segment, which just ended up snipping a single time-bin from _only one_ of the spectrograms, meaning they then …
> Fixed corner-case failure in math operations

- gwsumm/plot/triggers.py
- gwsumm/tabs/data.py
- gwsumm/tabs/etg.py
On the production DetChar summary pages, there has been an issue with PyCBC Live triggers where the sub-tabs for [**short**](https://ldas-jobs.ligo-la.caltech.edu/~detchar/summary/day/20181109/detchar/pycbc_live_short/), [**medium**](https://ldas-jobs.ligo-la.caltech.edu/~detchar/summary/day/20181109/detchar/pycbc_live_medium/), and [**long**](https://ldas-jobs.ligo-la.caltech.edu/~detchar/summary/day/20181109/detchar/pycbc_live_long/)-template duration triggers all actually show short-duration triggers. @tjma12 and I tracked this down and determined that, whenever triggers from one ETG are read (from PyCBC Live, say), any `event-filter` gets applied to them in-place and all subsequent filters will be ignored.
This PR fixes the issue by applying ETG `event-filter`s only before plotting …
> Do not process ETG table filters in-place

- gwsumm/triggers.py
This PR simplifies the `.meta` dict for tables read with `gwsumm.triggers.get_triggers`, mainly to prevent errors when writing these tables to the HDF5 archives.
> Simplified metadata for tables read with get_triggers

- bin/gw_summary
- gwsumm/html/bootstrap.py
- gwsumm/tabs/core.py
By request of the LIGO commissioning team, this PR updates the hard-coded `Report an Issue` link at the bottom of the output page, making this a configurable option that by default points to [`https://github.com/gwpy/gwsumm/issues`](https://github.com/gwpy/gwsumm/issues).
> Update the hard-coded Report an Issue link

- gwsumm/tests/test_plot.py
This PR removes one last `gwpy.plotter` reference from the test suite.
> Removed last `gwpy.plotter` reference

- gwsumm/plot/core.py
We need (for now) to separately escape the axes/figure titles (labels). This was removed in #213, but is actually required.
> Reinstated escaping of axis titles

- gwsumm/data/coherence.py
This PR fixes a bug in calculating coherence for short segments; `gwpy`'s spectrogram actually uses chunks of length `stride+overlap`, so we need to exclude segments shorter than that when calculating coherence.
> Fixed corner-case bug in calculating coherence on short segments

- gwsumm/plot/builtin.py
This PR is similar to 31b89d296e59e9f64fe192c0f906d94d94eb5d68 (#215) but for the spectrogram case.
> Added more protection against empty data in plotting

- gwsumm/plot/__init__.py
This pull request adjusts the summary page `rcParams` for gwpy-0.13.0 so that they continue to use LaTeX for plot rendering.
[**Here**](https://ldas-jobs.ligo-la.caltech.edu/~aurban/summary/formatting/1233522844-1233523759/) is a thorough example of pages with plots rendered under the proposed changes (requires `LIGO.ORG` credentials).
cc @duncanmmacleod, @tjma12
> Adjust plot settings for gwpy-0.13.0

- gwsumm/data/mathutils.py
This PR attempts to resolve an issue with gwpy-0.13.0/astropy. It allows `gwsumm.data.mathutils` to support adding floats to channels by assigning them the same unit as the base `Series` object.
> Support float operations by assigning them the same unit as the base Series

- gwsumm/plot/__init__.py
This PR reproduces the `GWPY_TEX_RCPARAMS` settings so that summary page plots are rendered with LaTeX, as before. Example output made with these changes is available [**here**](https://ldas-jobs.ligo-la.caltech.edu/~aurban/summary/1233522844-1233523759/cal/h_t_generation/).
> Reproduce GWPY_TEX_RCPARAMS for use with gwpy-0.13+

- gwsumm/data/utils.py
- gwsumm/plot/__init__.py
- gwsumm/tests/test_data.py
- requirements.txt
- setup.py
This PR tweaks the `rcParams` to only use TeX to render plots if TeX is available on the local system, otherwise `text.usetex` is set to `False`.
Because `gwsumm` requires the development version of `gwpy`, which will soon be packaged into gwpy-0.14.0, this PR also makes the following changes:
* Switch out an import of `gwpy.signal.fft` with its replacement module in the pre-release branch, `gwpy.signal.spectral`
* Require `scipy>=1.2.0` in order to support median power spectral densities
> Avoid build test failures

- gwsumm/data/timeseries.py
This PR updates `gwsumm.data.timeseries` to detect when the requested resample rate matches the current rate, emit a warning, and then just skip it, rather than attempting to resample and erroring (as of gwpy-0.14.0, see gwpy/gwpy#1073).
> Warn about noop resampling in gwsumm.data, but don't error

- gwsumm/html/bootstrap.py
- gwsumm/html/utils.py
- requirements.txt
- setup.py
This PR uses the `pygments` package to render `about` pages with syntax highlighting in configuration files. This does away with a call to `subprocess` and resolves a python3 compatibility issue, as we've seen elsewhere that the `highlight` command line tool leads to malformed html in python-3.x.
Note, `pygments` is available through both PyPI (`pip install pygments`) and Conda (`conda install pygments`) and is compatible with python-3.x. These changes are also consistent with gwdetchar/gwdetchar#251 and gwdetchar/hveto#112.
Test `gw_summary` output is available [**here**](https://ldas-jobs.ligo-la.caltech.edu/~aurban/summary/day/20190223/about/index.html), made within an environment running python-2.7 (requires `LIGO.ORG` credentials).
>  Use pygments to render config files

- gwsumm/plot/range.py
- gwsumm/plot/segments.py
This PR hauls in an ancient utility from older versions of gwpy to resolve an issue preventing segments and BNS range histograms from running properly, and removes deprecated kwargs. This is needed in order to deliver ER14 summary pages for LIGO Hanford and Livingston.
Test output produced with these changes is available [**here**](https://ldas-jobs.ligo.caltech.edu/~alexander.urban/summary/ER14-test/1236002400-1236074400/) (requires `LIGO.ORG` credentials). Something is wrong with datafind, so many of the plots are empty, but formatted correctly.
> Bugfix for segment histograms

- gwsumm/data/mathutils.py
- gwsumm/plot/noisebudget.py
This PR fixes a bug to allow noise budgets to actually run when we have `OBSERVATION_READY` data. [**Here**](https://ldas-jobs.ligo-la.caltech.edu/~detchar/summary/day/20190308/isc/noise_budget/) is a recent ISC noise budget page for Livingston (requires `LIGO.ORG` credentials), where I have applied these changes as a hotfix.
> Resolve a bug in ISC noise budget plots

- gwsumm/tests/test_data.py
- gwsumm/triggers.py
This PR modifies the necessary modules to import `CacheEntry` from `lal.utils` and not from `glue.lal` where it has been deprecated.
> Use CacheEntry from lal.utils

- gwsumm/plot/segments.py
This PR implements a proper fix for histogram axes when the `sep` kwarg is set to `True`. See [**here**](https://ldas-jobs.ligo.caltech.edu/~alexander.urban/summary/ER14-test/1236002400-1236074400/segments/) for an example (requires `LIGO.ORG` credentials).
> Proper fix for histogram axes when sep=True

- gwsumm/tabs/core.py
This PR re-orders "blessed" tabs so that `Home` comes first, followed by `Summary`. (Not very interesting) test output is available [**here**](https://ldas-jobs.ligo-la.caltech.edu/~aurban/summary/1236906455-1236906460/), the pertinent bit is the top navbar.
> Re-order default tabs so Home is first

- gwsumm/tabs/gracedb.py
This PR adjusts `gwsumm.tabs.gracedb` so that requested GraceDb queries look for superevents first, and if that fails, fall back to "standard" events (which allows us to still support external triggers).
[**Here**](https://ldas-jobs.ligo-la.caltech.edu/~aurban/summary/day/20190319/analysis/gw_events/) is a (so far empty) page of GW events, and [**here**](https://ldas-jobs.ligo-la.caltech.edu/~aurban/summary/day/20190319/analysis/exttrig/) is a page of GRBs demonstrating the query still works.
> Use superevents in gracedb queries

- gwsumm/plot/segments.py
This PR inverts bit streams configured to display '1' as a 'bad' state, rather than only inverting the colors. Test output is available [**here**](https://ldas-jobs.ligo-la.caltech.edu/~aurban/summary/day/20190319/sqz/overview/) (see the top-right statevector plot in particular).
> (Invert flags whose active state is) considered harmful

- bin/gwsumm-plot-guardian
This PR adds a `-s/--section` command-line option to the `gwsumm-plot-guardian` script, to allow using a section not named `tab-{node}`.
> Added --section option to gwsumm-plot-guardian

- gwsumm/html/bootstrap.py
- requirements.txt
- setup.py
This PR removes the custom (broken) calls to `pip` with calls out to `gwdetchar.io.html` to build an HTML table of the packages in the current environment.
As a result, this adds `gwdetchar >=0.3.0` as a dependency.
> Use gwdetchar for HTML package table

- gwsumm/html/tables.py
- gwsumm/tabs/data.py
- gwsumm/tabs/etg.py
- gwsumm/tabs/gracedb.py
- gwsumm/tabs/guardian.py
- gwsumm/tabs/management.py
- gwsumm/tabs/sei.py
- share/js/gwsumm.js
- share/sass/gwsumm.scss
By request of the Livingston management, this PR allows users to export HTML tables to a CSV file. The idea is to only perform this action when it's requested, by providing a bootstrap button whose `onclick` action converts the HTML to CSV using javascript.
The following changes are included:
* Include javascript tools that identify HTML table elements by ID, parse them, and convert to a downloadable CSV blob
* Whenever an `id` is assigned to an HTML table element, include a bootstrap button whose `onclick` action invokes these javascript tools
* Assign `id`s to all HTML tables except the SEI watchdog trips, since they already have a downloadable file
* Remove commas from date formatting, since they pollute the CSV
A full suite of test pages, with several tabs showing a CSV button in …
> Export HTML tables to CSV using javascript

- bin/gw_summary
This PR improves condor checkpointing by writing an HDF5 summary after processing every tab, rather than only once at the very end. This will help speed up processing whenever one tab fails.
This fixes #243.
> Write HDF5 summary after every tab

- gwsumm/plot/range.py
This PR implements a couple of protections against miscellaneous network range issues:
* If not all BNS range timeseries are the same length (e.g., if data flow is interrupted between sites), choose the shortest and compute the effective network range only up to that point
* Display BNS time-volume in units of `Mpc^3 kyr`
These changes are already hot-fixed on the CIT cluster, so they are tested in production. See [**here**](https://ldas-jobs.ligo.caltech.edu/~detchar/summary/1238166018-1240758018/range/) for output (requires `LIGO.ORG` credentials).
> Added protections against network range issues

- gwsumm/tabs/gracedb.py
This PR updates the logic in the context settings for the GraceDBTab so that an event is labelled with the 'success' context, designed to highlight interesting events, if it has the `GCN_PRELIM_SENT` label, without requiring any others.
> Label graceDB events just by GCN_PRELIM_SENT label

- bin/gw_summary
- bin/gwsumm-plot-guardian
- gwsumm/config.py
- gwsumm/data/timeseries.py
- gwsumm/plot/segments.py
- gwsumm/plot/sei.py
- gwsumm/segments.py
- gwsumm/state/core.py
- gwsumm/tabs/builtin.py
- gwsumm/tabs/core.py
- gwsumm/tabs/data.py
- gwsumm/tabs/etg.py
- gwsumm/tabs/gracedb.py
- gwsumm/tabs/guardian.py
- gwsumm/tabs/management.py
- gwsumm/tabs/sei.py
- gwsumm/tests/test_config.py
- gwsumm/tests/test_plot.py
- requirements.txt
- setup.py
This PR updates the dependencies to use the backports `configparser` package for python < 3.6. This allows us to simplify the imports of that module to use up-to-date ('python3') names, removing the need for `six` at least in this case, and removing ambiguity about which package (stdlib `configparser`, backports `configparser`, or stdlib `ConfigParser`) will be used at runtime.
> Use backports configparser package for python < 3.6

- .codecov.yml
- .travis.yml
- README.md
This PR updates the CI to use codecov, it's a bit more feature-complete compared to coveralls.
> Use codecov for coverage

- gwsumm/tabs/gracedb.py
This PR implements a few updates to the gracedb event tabs:
- use `<samp></samp>` to display labels
- include web interface query URL below results table
- use bootstrap buttons for gracedb event page links
The current O3 summary page is already using these changes, and can be used as a faithful example. Otherwise, a second example is [here](https://ldas-jobs.ligo.caltech.edu/~duncan.macleod/summary/testing/1238166018-1240758018/analysis/gw_events/) [LIGO.ORG].
> More updates to gracedb event tabs

- bin/gw_summary
- gwsumm/tabs/core.py
I've made a few changes that fix some problems that I was seeing when trying to run gwsummary in a Python 3.7 environment.
> Python 3 compatibility fixes

- gwsumm/tabs/core.py
The previous PR #253 didn't fix a more fundamental problem that Python 3 does not use the __metaclass__ attribute. To fix this you can use the `six.add_metaclass` decorator, which is what this PR does. It also removes a "fix" from #253 that is no longer necessary.
> Make __metaclass__ setting for the Tab Python 3 compatible

- gwsumm/plot/triggers.py
This PR replaces calls to `Plot.add_legend` with calls to `Axes.legend` - the former was removed a few gwpy releases ago.
> Fixed use of Plot.add_legend

- gwsumm/archive.py
- gwsumm/tabs/etg.py
- gwsumm/tabs/sei.py
This PR fixes three bugs found when testing deployment with python3.
> Fixed a few issues discovered in testing on python3

- gwsumm/plot/mixins.py
This PR fixes one missed metaclass definition, to finalize dropping python2 support.
> Fix a metaclass definition for python3

- gwsumm/tabs/core.py
This PR takes advantage of new functionality in `gwdetchar.io.html.new_bootstrap_page` to restore the correct `staticpath` for CSS and JS files. See also gwdetchar/gwdetchar#337.
> Restore the correct staticpath

- gwsumm/data/coherence.py
This PR fixes a corner case in coherencegrams, where segments that are a superset of the spans of individual inputs lead to a `ValueError`. The fix crops channels using the intersection of all inputs, something like:
```python
import operator
from functools import reduce
spans = [series.span for series in inputs]
reduce(operator.and_, spans, new_segment)
```
> Bugfix for coherencegram segment overlaps

- bin/gw_scan_loudest
- bin/gw_summary
- bin/gwsumm-plot-triggers
This PR stops reading cache files as `bytes` objects, for backwards-compatibility with cache files written in python2.
> Use backwards-compatible cache file reading

- gwsumm/tabs/data.py
This PR fixes a(n evidently) longstanding bug where segment caches fail to get passed properly to the `finalize_states` method when constructing data tabs.
cc @duncanmmacleod, @madeline-wade
> Pass segment cache to finalize_states, if available

- gwsumm/html/html5.py
- gwsumm/html/tests/test_html5.py
- gwsumm/tabs/etg.py
This PR refactors the `html.html5.ldvw_qscan` utility to support batch omega scans through LDVW. It also adds a new unit test for the refactored functionality.
Example output is available [**here**](https://ldas-jobs.ligo-la.caltech.edu/~aurban/summary/day/20190702/detchar/pycbc_live_short/).
cc @areeda, @duncanmmacleod
> Refactor ldvw_qscan to support batch qscans

- gwsumm/html/bootstrap.py
- gwsumm/tabs/core.py
- gwsumm/tabs/data.py
- gwsumm/tabs/etg.py
- gwsumm/tabs/fscan.py
- gwsumm/tabs/guardian.py
- gwsumm/tabs/misc.py
- gwsumm/tabs/sei.py
- gwsumm/tabs/stamp.py
This PR refactors and simplifies construction of bootstrap alert boxes by taking advantage of the brand-new `gwdetchar.io.html.alert` utility available in gwdetchar-1.0.0 (pre-release). Various PEP-8 compliance fixes are also included.
> Use the gwdetchar.io.html.alert utility to render bootstrap alert boxes

- gwsumm/tabs/fscan.py
This PR fixes the arrangement of Fscan buttons so that they have 4 to a row, befitting their configuration in O3. It also includes one PEP-8 compliance fix.
> Fix the arrangement of Fscan buttons

- gwsumm/html/html5.py
- gwsumm/html/static.py
- gwsumm/html/tests/test_html5.py
- gwsumm/html/tests/test_static.py
- gwsumm/tabs/builtin.py
- gwsumm/tabs/core.py
- requirements.txt
- setup.py
- share/js/gwsumm.js
- share/sass/gwsumm.scss
This PR allows us to publish user-side release notes and help content for the summary pages. The notes themselves will be taken from configuration files, then wrapped in HTML and displayed in a `dialog` element. The user-facing way to activate this feature is a floating, sticky button showing a question mark.
Two dependencies are introduced:
* Because many modern browsers do not natively support the `dialog` element (see [**this reference**](https://caniuse.com/#feat=dialog)), I'm importing a [**polyfill**](https://github.com/GoogleChrome/dialog-polyfill) that is widely compatible.
* As a trade-off between ability to customize and ease of use, the [**python-markdown**](https://python-markdown.github.io/reference/) library is used to render release notes. This allows users to write notes …
> Display release notes and help content in a dialog box

- gwsumm/segments.py
This PR fixes a bug in reading segment caches by properly testing that `cache` is a file path object before attempting to determine its file extension.
cc @Madeline-wade
> Properly test for cache types

- gwsumm/data/range.py
- gwsumm/plot/builtin.py
- gwsumm/plot/range.py
This PR registers new plot types necessary to display a couple of requested figures-of-merit on the LIGO DetChar summary pages. The plot types added are:
* Range spectrograms, i.e. time-frequency maps of the range integrand based on spectrograms of _h(t)_
* Percentile spectra based on these range spectrograms
* Cumulative integrals of the median range integrand, showing the fraction of range accumulated as a function of frequency
Standard plots of BNS range timeseries trends are also simplified. An example showing all the newly registered plot types made with LIGO-Livingston data is available [**here**](https://ldas-jobs.ligo.caltech.edu/~alexander.urban/summary/testing/day/20190628/) (requires `LIGO.ORG` credentials). Another example with [**multiple …
> Register new plot types for astrophysical range

- gwsumm/data/coherence.py
This PR gracefully handles the use case where coherence analysis segments are non-empty, but no data are found in the frame archive, by wrapping the sample rate in a try-except block.
Note, this change has been successfully tested in production at LIGO-Livingston.
> Gracefully handle coherence gaps

- share/js/gwsumm.js
This PR attempts to set links constructed with bootstrap-datepicker, particularly the `Today` link at the bottom of the calendar, to use UTC rather than the local timezone of the browser. This is to avoid browser-side issues for users in timezones east of London, who currently see links to a nonexistent page for at least one hour each day.
This PR also sets the calendar to begin on Sunday rather than Monday.
Example output is available [**here**](https://ldas-jobs.ligo.caltech.edu/~alexander.urban/summary/testing/day/20190902/).
> Force timezone to UTC for javascript utilities

- gwsumm/html/html5.py
- gwsumm/html/tests/test_html5.py
This PR adds functionality to resolve symbolic links when pointing to external pages. Specifically, it is designed to support production hveto runs, which are processed three times a day with a symbolic link pointing to the latest analysis.
cc @duncanmmacleod, @areeda
> Resolve symbolic links when pointing to external pages

- gwsumm/data/timeseries.py
- gwsumm/tabs/guardian.py
- gwsumm/tabs/sei.py
This PR explicitly optimizes over KAGRA ADC frametypes (commissioning, raw, and trends), similar to those for H1 and L1. It also includes support for KAGRA's local timezone when displaying Guardian state transition tables and SEI watchdog trips.
> Optimize KAGRA ADC frametypes

- gwsumm/data/timeseries.py
In the current code, when a cache file is passed to `get_timeseries_dict`, it assigns the frametype of the first channel to all channels listed in the config (in the `frametypes` dict on `L469`) and attempts to read all channels from this frametype. This causes failures when a cache file contains frames of more than one type. After this change, users can define frametypes for several channels in a config file and they will all be read from frames correctly. If frametypes are not provided in the config, the standard process for guessing a frametype will commence.
Tested this with a cache file that contains several frametypes: https://ldas-jobs.ligo.caltech.edu/~thomas.massinger/detchar/nonsens-review/summary/C01/day/20190418/compare_strain/
And tested on a config that reads directly from …
> Discover frametype dynamically if passed a cache file

- gwsumm/tabs/gracedb.py
This PR enables direct links to data-quality reports for specific GraceDb superevents. It also pedantically changes many double-quote characters (`"`) to single-quotes (`'`) purely for self-consistency.
See [**here**](https://ldas-jobs.ligo.caltech.edu/~alexander.urban/summary/day/20190930/analysis/gw_events/) for a rendered example (requires `LIGO.ORG` credentials).
cc @duncanmmacleod, @areeda
> Link to DQR from GW Events tables

- .stylelintrc.yml
- .travis.yml
- setup.py
- share/sass/gwsumm.scss
This PR implements an additional build-and-test phase for JavaScript elements using `acorn`, and for CSS elements using `stylelint` and standard SASS guidelines. The `gwsumm.scss` source file is corrected for a number of linting complaints.
This also explicitly requires `flake8` and `pytest-cov` from the `setup.py` script.
> Implement acorn checks for GWSumm JavaScript

- gwsumm/html/html5.py
- gwsumm/html/tests/test_html5.py
- gwsumm/tabs/builtin.py
- gwsumm/tabs/core.py
- requirements.txt
This PR implements a feature allowing users to select and overlay plots from across the summary pages, a feature request based on feedback from LIGO data-quality shifts during O3, see [**here**](https://git.ligo.org/detchar/ligo-summary-pages/issues/121) for the original issue ticket. Also included are a few minor icon replacements and other edits related to consistency with pre-release gwdetchar.
See [**here**](https://ldas-jobs.ligo.caltech.edu/~alexander.urban/summary/testing/1242518418-1242522018/) for example output showing the plot overlay feature in action (requires `LIGO.ORG` credentials). Note, image selections are saved in session storage, so they will be remembered across a change of tabs up to and until the user navigates away from a GWSumm output page. For the upstream …
> Allow users to select and overlay plots

- gwsumm/html/static.py
- gwsumm/html/tests/test_static.py
This PR upgrades the jQuery dependence to 3.4.1, as the jQuery 3.x series patches some (minor) security vulnerabilities.
> Upgrade to jQuery-3.4.1

- gwsumm/html/bootstrap.py
- gwsumm/html/tests/test_bootstrap.py
- gwsumm/tabs/gracedb.py
- gwsumm/tabs/guardian.py
- gwsumm/tabs/sei.py
This PR takes advantage of a couple new event listeners added to `gwbootstrap` for button click actions, including for table-to-CSV conversion and the return-to-top button.
See also gwdetchar/gwbootstrap#9.
> Take advantage of event listeners in gwbootstrap

- gwsumm/tabs/builtin.py
- setup.py
This PR tweaks `setup.py` to copy over minified files from gwbootstrap, rather than building them directly. It also adds an extra identifier to figures rendered with fancybox:
```html
<a class="fancybox" data-fancybox="gallery" ...>
```
This ensures such figures will have a thumbnail view with flickable album of photos per page.
> Copy over minified files, rather than building them

- .gitmodules
- MANIFEST.in
- gwsumm/html/static.py
- gwsumm/html/tests/test_bootstrap.py
- gwsumm/tests/test_archive.py
- requirements.txt
- setup.py
This PR removes `gwbootstrap` as a submodule, drops custom setup modules for compiling CSS and JS, and grabs `gwbootstrap` over the content delivery network [`jsDelivr`](https://www.jsdelivr.com/package/npm/gwbootstrap?path=lib). It also bumps the `gwdetchar` version requirement to 1.0.0.
> Prefer content delivery over local submodule

- gwsumm/plot/__init__.py
- gwsumm/plot/builtin.py
- gwsumm/plot/core.py
- gwsumm/plot/guardian.py
- gwsumm/plot/mixins.py
- gwsumm/plot/noisebudget.py
- gwsumm/plot/range.py
- gwsumm/plot/segments.py
- gwsumm/plot/sei.py
- gwsumm/plot/triggers.py
- gwsumm/plot/utils.py
- gwsumm/tabs/guardian.py
- gwsumm/tabs/management.py
This PR replaces calls to `gwsumm.plots.utils.usetex_tex` with calls to `gwdetchar.plot.texify`. Note, this utility will not be available until gwdetchar-1.0.0.
> Replace usetex_tex with gwdetchar's texify utility

- gwsumm/plot/range.py
This PR supports nicely-formatted log-scale VT and cumulative VT plots by explicitly using `matplotlib.ticker.LogLocator` to set major tick locations.
> Support nicely-formatted log-scaled VT plots

- gwsumm/plot/noisebudget.py
This PR overcomes a bug discovered in production by enforcing unit consistency when calculating noise budgets.
> Enforce unit consistency when calculating noise budgets

- requirements.txt
- setup.py
This PR simply bumps the minimum supported numpy version to 1.16 in order to be consistent with astropy.
> Require numpy 1.16 for consistency with astropy

- gwsumm/plot/noisebudget.py
This PR fixes a bug in which noise budget tabs with no active analysis segments fail because the `sum_` iterator is initialized with zero length.
> Enforce shape of noise budget sum

- gwsumm/html/static.py
This PR bumps the version numbers used for various CSS stylesheets and JavaScript libraries, including `font-awesome`, `bootstrap`, and `gwbootstrap`.
> Bump version numbers for gwbootstrap, bootstrap, and font-awesome

- gwsumm/html/html5.py
- gwsumm/html/tests/test_html5.py
- gwsumm/tabs/data.py
- gwsumm/tabs/guardian.py
- gwsumm/tabs/misc.py
This PR takes advantage of bootstrap-4's `text-justify` class to justify text inside of alert boxes, and of gwbootstrap's new IFO-specific alert boxes.
> Use text-justify class on bootstrap alert boxes

- gwsumm/html/static.py
This PR bumps the gwbootstrap version to 1.2.1.
> Bump gwbootstrap to version 1.2.1

- bin/gw_summary
- gwsumm/plot/range.py
- gwsumm/plot/segments.py
This PR addresses a collection of warnings discovered in the production LIGO summary pages:
* `gwpy.signal.fft` has been deprecated in favor of `gwpy.signal.spectral`
* `astropy.units.Quantity` objects have an ambiguous truth value, so use their raw numerical value
* `matplotlib.cbook.iterable` has been deprecated, use `numpy.iterable` instead
* Minor reshuffling for a different PEP-8 aesthetic
> Address warnings discovered in production

- gwsumm/triggers.py
This PR removes the `treename` kwarg from the etg trigger reading arguments when the file format is not root. If this isn't removed, `EventTable.read()` tries to include `treename` when invoking other formats that don't use tree structures (like `ascii`). This kwarg is only set when `etg = 'cwb'`, so the logic I've included should be comprehensive for avoiding formatting errors.
> Remove treename kwarg if not using root format

- .travis.yml
- CONTRIBUTING.md
- bin/gw_summary
- bin/gwsumm-plot-guardian
- bin/gwsumm-plot-triggers
- gwsumm/_version.py
- gwsumm/config.py
- gwsumm/html/html5.py
- gwsumm/html/tests/test_html5.py
- gwsumm/tabs/gracedb.py
- gwsumm/tests/test_plot.py
- gwsumm/utils.py
- requirements.txt
- setup.cfg
- setup.py
This PR drops all support for python < 3.6 and adds explicit support for 3.8 and 3.9 through build tests. This includes the following:
* Overhaul the Travis CI configuration to enable Conda builds
* Refactor `setup.py` into the configuration file `setup.cfg`
* Update dependency version pins
* Resolve various flake8 linter complaints
> Support Python >= 3.6 with build-and-test

- gwsumm/plot/guardian/__main__.py
- gwsumm/plot/guardian/core.py
- gwsumm/plot/guardian/tests/__init__.py
- gwsumm/plot/guardian/tests/test_main.py
- gwsumm/plot/triggers/__main__.py
- gwsumm/plot/triggers/tests/__init__.py
- gwsumm/plot/triggers/tests/test_main.py
- setup.cfg
This PR seeks to improve GWSumm's coverage by implementing unit tests for `gwsumm.plot.guardian.__main__` and `gwsumm.plot.triggers.__main__`, which touch other modules in the codebase.
A similar treatment of `gwsumm.__main__` and `gwsumm.batch` is forthcoming.
> Implement unit tests for gwsumm.plot.{guardian,triggers}

- gwsumm/plot/segments.py
This PR fixes a bug in segment livetime pie charts, by normalizing the fractional duty cycle to the total analyzed wall-clock time rather than the sum of all segments. See [**this page**](https://ldas-jobs.ligo.caltech.edu/~detchar/summary/1256655618-1269363618/segments/) (cf. bottom row of plots and "Segment information" table) for an example run in production.
cc @tjma12, @duncanmmacleod
> Adjust normalization of segment livetime pie charts

- gwsumm/batch.py
- gwsumm/tests/test_utils.py
- gwsumm/utils.py
This PR patches `gwsumm.batch` to launch `python -m gwsumm` jobs to Condor, rather than `gw_summary`, thus fixing an issue seen in production when writing HDF5 archives. (That issue amounts to a `str`/`bytes` incompatibility.)
This fixes #324.
> Run python module under Condor

- gwsumm/archive.py
This PR applies a band-aid to an error I'm seeing in production, in which `gwsumm.archive._write_data` fails on writing `StateVector` objects because of byte representation.
> Catch TypeErrors that arise writing StateVector objects

- .travis.yml
This PR pins the download reference for the `parse-conda-requirements.py` script, since the upstream gwpy is changing (see gwpy/gwpy#1320).
> Pin parse-conda-requirements.py to a specific version

- gwsumm/tabs/fscan.py
Bring the Line Count statistic to the top of the Fscan pages and separate them from the 'spectra' section. Drop alphabetical organization of the Fscan detail pages (it was previously sorted as 'Coherence Daily', 'Coherence Monthly', and 'Coherence Weekly'; now it doesn't have a sorting so it relies on the configuration file for organization).
With the configuration file, the Fscan pages are properly sorted as 'Daily', 'Weekly', and 'Monthly'.
Example new output:
https://ldas-jobs.ligo-wa.caltech.edu/~evan.goetz/summary/day/20210427/detchar/fscan/
I suppose this would require a point release to bring in the new page format to production summary pages.
> Update the Fscan pages with new figure of merit

- gwsumm/triggers.py
- setup.cfg
This PR migrates the `gwsum.triggers` module to use `python-ligo-lw` for handling LIGO_LW files, instead of `glue.ligolw`.
All of the actual reading is done by GWpy, so this change doesn't actually change how the files are read, but instead modifies some edge cases (e.g. empty table creation, etc).
> Migrate LIGO_LW handling to use python-ligo-lw

- gwsumm/data/timeseries.py
- setup.cfg
This PR updates the usage of `gwdatafind` to be compatible with >=1.1.0.
> Update gwdatafind usage for new interface

- docs/tabs/websites.rst
Closes #179
Simply change the broken link to one that works.
> Fix broken docs link

- gwsumm/tabs/core.py
Closes #334
Simple fix when no list of tabs is given, then no navbar should be created.
> When no list of tabs is given, write_html() fails

- gwsumm/html/static.py
What it says on the tin: point to the newest version of gwbootstrap
> Bump gwbootstrap 1.3.1 up to 1.3.2

- gwsumm/archive.py
Sometimes the HDF5 file is corrupted on the cluster and it causes the summary page job to fail. The only way to recover is to remove the corrupted file and then resubmit the failed job.
This change tries to open the file, but if there is an OSError raised, then the source file can be removed before continuing. Since no data is loaded, it is as if the file doesn't exist anyway. I think this should solve our recurring issues on the cluster regarding corrupted HDF5 files
Closes #344
> Use try-except when reading in an archive HDF5 file

- gwsumm/plot/triggers/__main__.py
- gwsumm/plot/triggers/core.py
- setup.cfg
> Handle changes in kwarg defaults in Axes.scatter (take 2)

- gwsumm/__main__.py
According to everything I can gather, the summary page configuration should not require an [html] section and an issues key-value pair to generate a simple page. However, the case where no [html] section is provided is not caught and so an error is produced. This PR fixes the issue
Closes #348 (at least the issue pointed out here, though not fully addressing all the question about the documentation far out of date. I'll be addressing that separately)
> Fix when no html section given in configuration

- gwsumm/plot/builtin.py
Apparently this fails in recent versions of `matplotlib`:
```
ax.pcolormesh([1, 10], [1, 10], [[1, 10]], visible=False, **plotargs)
```
with error:
```
TypeError: Dimensions of C (1, 2) are incompatible with X (2) and/or Y (2); see help(pcolormesh)
```
It should instead be
```
ax.pcolormesh([1, 10], [1, 10], [[1, 10], [1, 10]], visible=False, **plotargs)
```
> Fix pcolormesh call in newer matplotlib versions

- gwsumm/triggers.py
As pointed out in https://github.com/gwpy/gwpy/issues/1334, the `EventTable.read()` method will fail if there are zero length trigger files in addition to non-zero length trigger files. This is due to a column type mismatch.
As a workaround, we read the trigger files one-by-one and drop any files from the cache that are zero length tables. This should fix continued failures until `gwpy` is fixed to address this issue.
> Workaround for when there are zero length trigger files in the cache

- gwsumm/triggers.py
This fixes a problem with removing trigger files from the cache that have zero-length. The problem is that the previous way of doing this would not iterate properly.
> Fix cache file check for zero length trigger files

- gwsumm/state/core.py
Currently the "hours" option in a state is broken because the value for the day start is not being saved in the code. Basically the replace() method for a datetime object does not change the value in-place, it just returns the value. So essentially, all the broken code was doing was stating the day start but not actually using it. This fixes the problem
> Bugfix for when hours are requested in a state

- gwsumm/plot/range.py
This PR adds support for specifying the `range_func` when generating range-related plots. This is done using a dictionary of methods, meaning that if new methods are added to gwpy, this dict needs to be updated accordingly. 
An example of this functionality can be seen here in the bottom left plot (requires LIGO.org credentials):
https://ldas-jobs.ligo-wa.caltech.edu/~derek.davis/detchar/preO4/summary_test/noise_sub_page/day/20230328/cal/nonsens/
> Add support for specifying range method

- gwsumm/data/timeseries.py
This PR adds mapping for the aggregated HOFT_TEST to the 1-s long DMT_TEST frames
> Add mapping for HOFT_TEST frames

- gwsumm/data/timeseries.py
This PR patches `gwsumm.data.timeseries` to define `{H1,L1}_llhoft` as the 1-second equivalent of `{H1,L1}_HOFT_C00`, rather than the equivalent `*_DMT_C00` frames. The `llhoft` files are the official low-latency product that are cached for a period (~1 month) on LDAS and discoverable with `gwdatafind`.
> Use llhoft as short type for LIGO aggregated h(t)

- gwsumm/data/timeseries.py
This PR changes the V1 frametype mapping for HoftOnline channels to use a backup V1_llhoft frametype
This should be merged and deployed carefully since until the configuration file are appropriately changed, the deployment could break the network summary pages
> Change the V1 h(t) mapping from original frame type to backup frame type

- gwsumm/__main__.py
- gwsumm/archive.py
It changes the structure of the archiving function.  Instead of moving the current backup to a temporary file, it now creates a temporary file for the new saved data. This new file is only moved to its proper place if there are no issues, making sure the backup is secure, even if there's a saving error.
This PR replaces #372.
> Safer archive process

- .readthedocs.yaml
- docs/conf.py
This PR updates the readthedocs configuration file. See https://blog.readthedocs.com/migrate-configuration-v2/
> Update readthedocs configuration

- gwsumm/plot/range.py
This PR addresses #381 so that the combined VT calculation is correct in all cases where data from at least one detector is missing. 
In cases where data is entirely missing from one detector, this detector also is no longer considered during the combined VT calculation. 
This PR can be tested by running the O4a summary command with the production archive file.
> Fix case when data is missing at beginning of vt span

- gwsumm/plot/builtin.py
- gwsumm/plot/core.py
- gwsumm/plot/noisebudget.py
- gwsumm/plot/segments.py
- gwsumm/plot/triggers/core.py
- pyproject.toml
This PR updates the Axes.grid keyword arguments to use `visible` that is needed because of upstream `matplotlib` updates.
This PR replaces #368
> Update Axes.grid keyword to use 'visible'

- gwsumm/tests/test_plot.py
This PR fixes an `ImportError` related to the `gwpy.plot.tex.HAS_TEX` global variable, which was removed in 3.0.8, by replacing it with a call to `has_tex()`, which does exactly the same thing.
> Update usage of GWpy's has_tex

- gwsumm/archive.py
#378 changed the creation of the archive file from a temporary file, to avoid loosing backups. By construction, [`NamedTemporaryFile` gives sets the permission to 600](https://stackoverflow.com/a/10541972). In this PR the permission of the newly created archive file is reset to 664, which grants reading permission to any user.
> Add reading permission to the archive file

- gwsumm/plot/segments.py
- gwsumm/segments.py
This PR addresses a problem that there could be gaps in the segments, thus resulting in pie chart plots that can remain unfilled.
Here is an example for O4a.3: https://ldas-jobs.ligo.caltech.edu/~evan.goetz/summary/gps/1384873218-1389456018/segments/
Here is an example for "O4a.4" Dec 1 2023 - Jan 31 2024 ran on Jan 25 2024: https://ldas-jobs.ligo.caltech.edu/~evan.goetz/summary/gps/1385424018-1390694418/segments/
For reference, this is what the "O4a.4" interval run using the current gwsumm code: https://ldas-jobs.ligo.caltech.edu/~evan.goetz/summary/gps/1385424018-1390694419/segments/
We might consider changing the colors for the single IFO pie wedges in the `.ini` configuration file since the red pie wedges tend to blend together. Or we can chose a different color for the "Missing …
> Fix for gaps in segments causing unfilled pie chart plots

- gwsumm/channels.py
Fix deprecation warnings for `Ndes2ChannelType.nds2names`
> Fix deprecation warning for Nds2ChannelType.nds2names

- gwsumm/plot/core.py
- gwsumm/tests/test_plot.py
This pull request introduces default `rcParams`, ensuring that plots have the desired appearance without the necessity of activating the `ligo-summary-3.10` Conda environment.
These parameters were obtained by comparing the `matplotlib.rcParams` differences between `igwn` and `ligo-summary-3.10` Conda environments.
> Add default `rcParams`

- gwsumm/plot/__init__.py
- gwsumm/plot/builtin.py
- gwsumm/plot/range.py
- gwsumm/tabs/data.py
This pull request introduces the `RangeCumulativeHistogramPlot` class, derived from `RangePlotMixin`. This new class facilitates the creation of cumulative density histograms within a specified range.
Additionally, this PR includes the option to enable automatic scaling of the histogram in Matplotlib. This can be achieved by setting `range = None` when defining it as `'autoscaling'`.  Similarly, the `'max'` and `'min'` options are also added to scale the histogram based on the data.
The `RangeCumulativeHistogramPlot` class will be computed from the $h(t)$ channel, therefore it is not the most efficient way to plot the cumulative histogram for the BNS range.  It is faster to use the `DMT-SNSL_EFFECTIVE_RANGE_MPC` channel and the standard `histogram` plot type to do so.
> Add RangeCumulativeHistogramPlot class

- gwsumm/triggers.py
This PR fixes the empty table where we want to extend the columns. There was a bug when using `extend('foo')`. It should be `extend(['foo'])`.
> Bugfix for empty trigger tables

- gwsumm/triggers.py
This PR updates the default omicron trigger reading behaviour from xml files to hdf5 files. This is needed especially for `gwsumm.plot.triggers` since there is no current input mechanism for deciding from which files to read triggers.
> Update default omicron trigger reading behaviour

- gwsumm/plot/segments.py
This PR moves an import of the `iterutils` module (not to be confused with the standard library module `itertools`) from `glue` to `lal`, the former has been deprecated for many years and is being removed.
> Import iterutils module from lal instead of glue

- docs/environment.yml
This PR attempts to hack around the current readthedocs build failure by avoiding a package that is corrupt in the cache.
> Avoid sphinx-automodapi 0.17.0 when building docs on RTD

- gwsumm/html/bootstrap.py
- gwsumm/html/tests/test_bootstrap.py
The state switcher menu was going off screen in the new bootstrap version. This fixes the issue. See fixed version:
https://ldas-jobs.ligo-wa.caltech.edu/~iara.ota/summary/day/20240319/lock/glitches/
> Fix state switcher menu going off screen

- gwsumm/data/range.py
- gwsumm/data/spectral.py
- gwsumm/plot/builtin.py
This PR addresses a bug related to computing the _spectrum_ for different states. Previously, the same spectrogram was being plotted for different states despite having different segments, due to a global variable storing spectrum data with identical keys for all states. This issue has been resolved by introducing the `state` argument to the `get_spectrum` and `get_spectrum_range` functions, using the state name as a key to differentiate spectrum data.
The original intention behind the removed snippet below
```python
if isinstance(segments, DataQualityFlag):	
name = ','.join([channel.ndsname, segments.name])
segments = segments.active
else:
name = channel.ndsname
```
was to incorporate the state into the `name` variable. However, this condition always failed because of the decorator …
> Fix spectrum plots for different states

- gwsumm/data/coherence.py
This PR addresses the issue encountered when computing coherence, which leads to a ValueError due to incompatible shapes, as illustrated in the following example:
```
ValueError: operands could not be broadcast together with shapes (734,8193) (9,8193) 
```
This problem often arises from utilizing the same channel across different coherence plots. It may occur when additional data is available during the computation of another plot, causing discrepancies in the segments of `globalv.COHERENCE_COMPONENTS` for that channel and the previously computed channel when saved to the HDF5 archive.
To tackle this issue, this PR ensures that all coherence components used have consistent segments within the globalv.COHERENCE_COMPONENTS variable.
To test this PR copy the corrupted archive located in …
> Fix coherence spectrogram archive problem

- gwsumm/data/range.py
This PR addresses the bug introduced in #403 by acknowledging that `globalv.SPECTROGRAMS` might not contain the specified `key`. In such cases, it now correctly returns an empty `SpectrogramList()`, according to the previously removed code snippet: 
```python
return globalv.SPECTROGRAMS.get(key, SpectrogramList())
```
> Properly handle empty dictionary in get_range_spectrogram

- gwsumm/html/static.py
- pyproject.toml
This PR updates the version pins for gwbootstrap in the code and gwdetchar in pyproject.toml
> Update version pins for gwbootstrap and gwdetchar

- gwsumm/data/coherence.py
- gwsumm/data/spectral.py
If the data is corrupted, the computed spectrograms may contain `nan` values. While these `nan` values are ignored in spectrogram plots, but they can cause issues in derived products such as the power spectral density and ratio spectrogram, where the presence of `nan` values leads to all values becoming `nan`, resulting in empty plots. This pull request addresses this issue by removing any potential `nan` values from the data used and saved in `globalv.SPECTROGRAMS`.
> Ignore `nan` spectrogram values

- gwsumm/plot/triggers/core.py
- pyproject.toml
This PR replaces `rstrip('.0')` with `removesuffix('.00')` to avoid removing any `0` before `.` in the string. See the examples below:
```
>>> a = "10.00" 
>>> b = "11.00" 
>>> c = "110.00"
>>> a.rstrip('.0')
'1'
>>> a.removesuffix('.00')
'10'
>>> b.rstrip('.0')
'11'
>>> b.removesuffix('.00')
'11'
>>> c.rstrip('.0')
'11'
>>> c.removesuffix('.00')
'110'
```
> Replace rstrip() with removesuffix() in triggers text

- .github/workflows/build.yml
- .readthedocs.yaml
This PR removes mamba with conda-incubator/setup-miniconda@v3 and from readthedocs configuration. It also comments out the github cache action as it seems to not be functioning properly. We can revisit whether we want to keep this going forward but for now it is commented out.
These changes enable the CI to work properly now.
> Update build.yml github actions and readthedocs OS/python

- pyproject.toml
This PR updates the project dependencies in `pyproject.toml` as follows
- remove max pin for `scipy`
- update pin for `gwpy` to require `>= 3.0.9` (the version that works with `scipy >= 1.14.0`)
> Unpin scipy with new gwpy pin

- .github/workflows/build.yml
This PR updates the setup-miniconda action configuration to restore cache functionality.
> Update setup-miniconda actions configuration

- docs/environment.yml
- gwsumm/data/timeseries.py
- gwsumm/data/utils.py
- pyproject.toml
We're using `gwpy.segments` everywhere else, so there's no need to have a direct usage of `igwn-segments`
> Remove direct usage of igwn-segments

- gwsumm/plot/builtin.py
This PR updates the method of calculating the cumulative range to be in line with Eq. 10 from https://arxiv.org/abs/2502.07253. This address multiple issues with the current calculation. This update requires no changes to existing configuration files used with `gwsumm`. 
A comparison of the cumulative range plot before and after this update can be seen below:
> Update formula for cumulative range

- gwsumm/batch.py
- gwsumm/tests/test_batch.py
This PR replaces X509 with scitokens. This may requires some downstream changes to the LIGO summary pages scripts
> Replace X509 with scitokens

- gwsumm/plot/builtin.py
- gwsumm/plot/core.py
- gwsumm/tabs/builtin.py
- gwsumm/tabs/data.py
This PR introduces a `statebar` configuration option, allowing users to choose to display the green/red bar for a selected state of time series plots in the "All" state tab.
[See this page](https://ldas-jobs.ligo-la.caltech.edu/~iara.ota/summary/day/20240820/sei/ground_blrms_overview/) for an example plot with the "Locked" state indicated by the bar. The configuration file should include:
```ini
[tab-blrms]
name = Ground motion BLRMS overview
statebar = Locked
shortname = Ground BLRMS overview
parent = SEI
...
```
> Add state bar

- gwsumm/__main__.py
- gwsumm/batch.py
- gwsumm/tabs/core.py
- gwsumm/tests/test_utils.py
- gwsumm/utils.py
This PR removes the custom checking if directories already exist by using the `exist_ok` option in `os.makedirs()`. This modest change is a small simplification step that improves code maintainability and standard python best practices
> Use standard exist_ok option when making directories

- pyproject.toml
This PR updates pyproject.toml to remove deprecation warnings displayed when building the package.
> Update pyproject.toml to remove deprecation warnings

- gwsumm/archive.py
See https://numpy.org/devdocs/release/2.0.0-notes.html#numpy-2-0-python-api-removals
This PR attempts to maintain backwards compatibility with older numpy versions
> unicode_ is renamed str_ in numpy2

- gwsumm/plot/noisebudget.py
- gwsumm/plot/sei.py
- gwsumm/tabs/sei.py
This PR fixes problems when plotting or processing in certain tabs when using modern `numpy` and `matplotlib` packages.
Specifically, there were API changes in more recent versions requiring changes to the behaviour how legends are reordered (in `plot/noisebudget.py`), axis labels are sized (in `plot/sei.py`), and how `numpy.nonzero` requires at least 1d sized arrays (in `tabs/sei.py`)
> Fix plotting and processing issues when using modern numpy/matplotlib

- gwsumm/__main__.py
- gwsumm/batch.py
- gwsumm/tests/test_archive.py
This PR adds to the batch jobs, the environment variables `XDG_CONFIG_HOME` and `XDG_CACHE_HOME` which crucially need to be accessible at all times, especially now that we're using scitokens. Since these are being inherited through `getenv=True`, setting these environment variables will override that, and beneficially should set us up for when we eventually remove `getenv=True`
> Set XDG_CONFIG_HOME and XDG_CACHE_HOME in batch jobs
